import type { AgentModePreset, PlannedTool } from "@/lib/agent-builder-types"

export const plannedTools: PlannedTool[] = [
  {
    slug: "terminal",
    name: "Terminal",
    category: "Developer",
    description: "Command execution surface for local build and debug loops.",
  },
  {
    slug: "file-system",
    name: "File System",
    category: "Developer",
    description: "Read and write workspace files inside explicit boundaries.",
  },
  {
    slug: "github",
    name: "GitHub",
    category: "Developer",
    description: "Issue, pull request, review, and repository automation.",
  },
  {
    slug: "browser",
    name: "Browser",
    category: "Research",
    description: "Web inspection and interaction for grounded research tasks.",
  },
  {
    slug: "api-client",
    name: "API Client",
    category: "Research",
    description: "Structured HTTP access for approved external APIs.",
  },
  {
    slug: "wallet-signer",
    name: "Wallet Signer",
    category: "On-chain",
    description: "Human-approved transaction signing boundary.",
  },
]

export const modePresets: AgentModePreset[] = [
  {
    mode: "personal-assistant",
    label: "Personal Assistant",
    badge: "Daily Operator",
    description: "Balanced private assistant for planning, drafting, and routine work.",
    artwork: {
      src: "/assets/agents/personal-assistant.png",
      alt: "Personal Assistant IronClaw persona",
      accent: "#38bdf8",
    },
    appearance: { avatar: "sentinel", theme: "iron" },
    skillSlugs: ["microsoft-365-workflow"],
    toolSlugs: ["microsoft-365"],
    plannedToolSlugs: [],
    defaultSoul: {
      name: "House Sentinel",
      mission: "Keep daily work organized, private, and ready for approval.",
      personality: "Calm, concise, protective, and practical.",
      autonomy: 45,
      privacyMode: "strict",
      memoryMode: "persistent",
      approvalPolicy: "manual",
    },
  },
  {
    mode: "developer-agent",
    label: "Developer Agent",
    badge: "Developer Focused",
    description: "Code-oriented builder for debugging, repo work, and release flow.",
    artwork: {
      src: "/assets/agents/developer-agent.png",
      alt: "Developer Agent IronClaw persona",
      accent: "#8b5cf6",
    },
    appearance: { avatar: "paladin", theme: "ember" },
    skillSlugs: [],
    toolSlugs: [],
    plannedToolSlugs: ["terminal", "file-system", "github", "browser"],
    defaultSoul: {
      name: "Dev Paladin",
      mission: "Ship clear, reviewed code with strong local verification.",
      personality: "Direct, exact, skeptical of weak assumptions, and implementation-focused.",
      autonomy: 70,
      privacyMode: "balanced",
      memoryMode: "session",
      approvalPolicy: "high-impact",
    },
  },
  {
    mode: "research-agent",
    label: "Research Agent",
    badge: "Evidence Mode",
    description: "Lower-autonomy researcher for source-backed synthesis.",
    artwork: {
      src: "/assets/agents/research-agent.png",
      alt: "Research Agent IronClaw persona",
      accent: "#34d399",
    },
    appearance: { avatar: "scholar", theme: "signal" },
    skillSlugs: [],
    toolSlugs: [],
    plannedToolSlugs: ["browser", "api-client"],
    defaultSoul: {
      name: "Signal Scholar",
      mission: "Find reliable evidence, compare sources, and produce grounded briefs.",
      personality: "Careful, citation-driven, neutral, and patient.",
      autonomy: 35,
      privacyMode: "strict",
      memoryMode: "session",
      approvalPolicy: "manual",
    },
  },
  {
    mode: "on-chain-agent",
    label: "On-chain Agent",
    badge: "Chain Aware",
    description: "NEAR-aware operator with explicit approval around chain actions.",
    artwork: {
      src: "/assets/agents/on-chain-agent.png",
      alt: "On-chain Agent IronClaw persona",
      accent: "#f59e0b",
    },
    appearance: { avatar: "oracle", theme: "arc" },
    skillSlugs: [],
    toolSlugs: ["near-rpc"],
    plannedToolSlugs: ["wallet-signer"],
    defaultSoul: {
      name: "Chain Oracle",
      mission: "Inspect chain state and prepare actions without crossing approval boundaries.",
      personality: "Precise, defensive, transaction-aware, and transparent.",
      autonomy: 60,
      privacyMode: "strict",
      memoryMode: "session",
      approvalPolicy: "manual",
    },
  },
  {
    mode: "security-agent",
    label: "Security Agent",
    badge: "Guard Mode",
    description: "Security-first agent for audits, monitoring, and threat analysis.",
    artwork: {
      src: "/assets/agents/security-agent.png",
      alt: "Security Agent IronClaw persona",
      accent: "#84cc16",
    },
    appearance: { avatar: "paladin", theme: "signal" },
    skillSlugs: [],
    toolSlugs: [],
    plannedToolSlugs: ["terminal", "file-system", "github", "browser"],
    defaultSoul: {
      name: "Guard Sentinel",
      mission: "Review systems for security issues and keep risky actions behind approval.",
      personality: "Careful, adversarial, evidence-driven, and explicit about residual risk.",
      autonomy: 50,
      privacyMode: "strict",
      memoryMode: "session",
      approvalPolicy: "manual",
    },
  },
  {
    mode: "data-analyst",
    label: "Data Analyst",
    badge: "Insight Mode",
    description: "Analyze datasets, generate reports, and surface operational insight.",
    artwork: {
      src: "/assets/agents/data-analyst.png",
      alt: "Data Analyst IronClaw persona",
      accent: "#22d3ee",
    },
    appearance: { avatar: "oracle", theme: "arc" },
    skillSlugs: ["microsoft-365-workflow"],
    toolSlugs: ["microsoft-365"],
    plannedToolSlugs: ["file-system", "api-client"],
    defaultSoul: {
      name: "Signal Analyst",
      mission: "Turn structured data into clear findings, charts, and next actions.",
      personality: "Precise, skeptical, quantitative, and concise.",
      autonomy: 55,
      privacyMode: "balanced",
      memoryMode: "session",
      approvalPolicy: "high-impact",
    },
  },
  {
    mode: "content-writer",
    label: "Content Writer",
    badge: "Creative Mode",
    description: "Draft, edit, and adapt content across formats and tones.",
    artwork: {
      src: "/assets/agents/content-writer.png",
      alt: "Content Writer IronClaw persona",
      accent: "#eab308",
    },
    appearance: { avatar: "scholar", theme: "ember" },
    skillSlugs: ["microsoft-365-workflow"],
    toolSlugs: ["microsoft-365"],
    plannedToolSlugs: ["browser"],
    defaultSoul: {
      name: "Draft Scribe",
      mission: "Create clear written material that matches audience, voice, and context.",
      personality: "Editorial, practical, structured, and direct.",
      autonomy: 62,
      privacyMode: "balanced",
      memoryMode: "persistent",
      approvalPolicy: "high-impact",
    },
  },
  {
    mode: "ops-agent",
    label: "Ops Agent",
    badge: "Automation Mode",
    description: "Coordinate workflows, systems, deployments, and repeated tasks.",
    artwork: {
      src: "/assets/agents/ops-agent.png",
      alt: "Ops Agent IronClaw persona",
      accent: "#60a5fa",
    },
    appearance: { avatar: "sentinel", theme: "iron" },
    skillSlugs: [],
    toolSlugs: [],
    plannedToolSlugs: ["terminal", "file-system", "github", "api-client"],
    defaultSoul: {
      name: "Ops Warden",
      mission: "Keep operational workflows moving with visible checkpoints and approvals.",
      personality: "Organized, calm, procedure-aware, and escalation-focused.",
      autonomy: 65,
      privacyMode: "balanced",
      memoryMode: "persistent",
      approvalPolicy: "high-impact",
    },
  },
  {
    mode: "trading-agent",
    label: "Trading Agent",
    badge: "Market Aware",
    description: "Track market context, compare signals, and prepare strategy notes.",
    artwork: {
      src: "/assets/agents/trading-agent.png",
      alt: "Trading Agent IronClaw persona",
      accent: "#65a30d",
    },
    appearance: { avatar: "oracle", theme: "signal" },
    skillSlugs: [],
    toolSlugs: ["near-rpc"],
    plannedToolSlugs: ["browser", "api-client", "wallet-signer"],
    defaultSoul: {
      name: "Market Oracle",
      mission: "Observe market data, explain tradeoffs, and keep execution human-approved.",
      personality: "Risk-aware, source-backed, numerical, and transparent.",
      autonomy: 45,
      privacyMode: "strict",
      memoryMode: "session",
      approvalPolicy: "manual",
    },
  },
  {
    mode: "custom",
    label: "Custom",
    badge: "Manual Build",
    description: "Blank loadout for assembling an agent from scratch.",
    artwork: {
      src: "/assets/agents/custom-agent.png",
      alt: "Custom Agent IronClaw persona",
      accent: "#7c3aed",
    },
    appearance: { avatar: "paladin", theme: "iron" },
    skillSlugs: [],
    toolSlugs: [],
    plannedToolSlugs: [],
    defaultSoul: {
      name: "Custom IronClaw",
      mission: "Define this agent's job before deployment.",
      personality: "Clear, focused, and aligned with owner instructions.",
      autonomy: 25,
      privacyMode: "strict",
      memoryMode: "off",
      approvalPolicy: "manual",
    },
  },
]

export function getModePreset(mode: AgentModePreset["mode"]) {
  return modePresets.find((preset) => preset.mode === mode) ?? modePresets[0]
}
